services:
  pythonapp:
    build: ./api/
    command: sh -c "sleep 10s; python -m api.app"
    depends_on:
      - mysql
  
  mysql:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABSE: 'test888spectate'
      MYSQL_ROOT_PASSWORD: 'Hashirs@10'

    